### ISSUE TITLE
The LoRA training codes and scripts

### ISSUE THREAD

**Issue by darkpromise98** [RLHF-V/RLAIF-V#11]
A significant achievement in aligning Vision-Language Models!

While running the code 'RLAIF-V/muffin/train/train_llava15.py', I noticed that all model parameters are trainable. Due to hardware limitations, could you kindly provide the LoRA training codes, similar to LLaVA?

**Comment by yiranyyu** [comment]
Thank you for your interest!

We are currently engaged in developing the LoRA codes, please stay tuned!

**Comment by yiranyyu** [comment]
We add the support of LoRA training and inference at [here](https://github.com/RLHF-V/RLAIF-V?tab=readme-ov-file#train). Sorry for the delay and we hope it could be helpful.
