### ISSUE TITLE
请问下divide的模型是额外finetune过的么？

### ISSUE THREAD

**Issue by menglin0320** [RLHF-V/RLAIF-V#12]
您好，感谢你们开源了这个项目，个人目前刚从比较lm的东西转到llm，觉得这个项目的思路和prompt对我有很大帮助。
有个问题想请教一下，我注意到你们的divide模型是要单独下载的，想问下这个模型单独finetune过么？论文里面更强调的是prompt。如果可以的话想了解下这方面是怎么做的。

**Comment by yiranyyu** [comment]
Thank you for your interest to our work! The model serve for division and conversion of claims are both trained as introduced in Appendix C.2 of our paper on arXiv. Please refer to the paper for more details.
