### ISSUE TITLE
Performance of POPE?

### ISSUE THREAD

**Issue by shufangxun** [RLHF-V/RLAIF-V#17]
Hi, what about the performance of POPE? It is a important benchmark to evaluate the object hallucination, which is widely reported in several papers.

**Comment by Haoye17** [comment]
Hello @shufangxun! Thank you for your interest in our work~

We do not evaluate our models on the POPE dataset, as the POPE dataset focuses solely on object existence hallucination of COCO images. Instead, we used a more comprehensive evaluation dataset, AMBER. AMBER also assesses the model's capability in hallucination discrimination, but it utilizes more diverse data sources and evaluates a broader range of hallucination types, making the results more reliable.

If you have any further questions, we are happy to assist!
