### ISSUE TITLE
divide and conquer

### ISSUE THREAD

**Issue by dreaming12580** [RLHF-V/RLAIF-V#18]
hai,   where is llama3-split and llama3-changeq model ?  how finetue llama3 to produce the two models ?

**Comment by Haoye17** [comment]
Hello! Thank you for your interest in our work~

You can download the [llama3-split](https://thunlp.oss-cn-qingdao.aliyuncs.com/rlaifv_llama3_split_model.tar.gz) and [llama3-changeq](https://thunlp.oss-cn-qingdao.aliyuncs.com/rlaifv_llama3_changeq_model.tar.gz) from here. 
When fine-tuning the Llama3 model, we first use prompts to guide the Llama3-70B model in splitting and converting, which helps us generate a set of training data. Afterward, we fine-tune the Llama3-8b model, using the code in llama-factory.

If you have any further questions, we are happy to assist!
