### ISSUE TITLE
Is there a paper or tech report to show the details of training and dataset

### ISSUE THREAD

**Issue by CrossLee1** [RLHF-V/RLAIF-V#2]
Is there a paper or tech report to show the details of training and dataset

**Comment by yiranyyu** [comment]
Sure! The paper will be released soon, probably tomorrow.

**Comment by CrossLee1** [comment]
@yiranyyu 
the divide-and-conquer approach looks great, and it seems work well on `detailed caption` task.
for `question answering` task, do you use the same method to divide the answers, how is it going?

**Comment by yiranyyu** [comment]
It works for `question answering` as well with the same dividing method. We think its effectiveness can be explained by two main reasons:

1. Models often provide more information than just the exact short answer (e.g. "left", "2", "no"). For example, given the question `How many dogs are in the image`, the model might answer it with `There is a dog in the left behind the sofa, and also a dog in the right under the table.  In summary, there are two dogs in the image`, which can be split into multiple claims.
2. Questions such as complex reasoning tasks require more than few words to answer.
