### ISSUE TITLE
When I use the cal_logp of all dataset,I met the question.This

### ISSUE THREAD

**Issue by XiaoLei2123** [RLHF-V/RLAIF-V#20]
![img_v3_02do_b346611a-ead2-4f84-9dd9-2b74cdc77afg](https://github.com/user-attachments/assets/68cee71a-4563-4597-b27b-4a26b3552c19)

**Comment by Haoye17** [comment]
Hi @XiaoLei2123, thanks for your interest in our work~

This error may occur when the size of a single parquet file is larger than 2GB. To deal with it, we previously updated our [code](https://github.com/RLHF-V/RLAIF-V/blob/main/muffin/eval/muffin_inference_logp.py#L307-L311) to save the final logp parquets in every 5000 samples, could you please update the code base to see if it still occurs?

If there are further questions, we are willing to help!

**Comment by XiaoLei2123** [comment]
Thank you for your reply.I will update my code to solve this question.

**Comment by XiaoLei2123** [comment]
If i want to solve this question , which python files I need to update?Can you offer a list about this question.Thank you!

**Comment by Haoye17** [comment]
Hi @XiaoLei2123 ! The files you need to update are:
- `muffin/data/datasets.py`: https://github.com/RLHF-V/RLAIF-V/blob/main/muffin/data/datasets.py
- `muffin/eval/muffin_inference_logp.py`: https://github.com/RLHF-V/RLAIF-V/blob/main/muffin/eval/muffin_inference_logp.py

You can try to see if this can help~
