### ISSUE TITLE
Would the data generation code be released?

### ISSUE THREAD

**Issue by Gaffey** [RLHF-V/RLAIF-V#21]
In this issue, it is said that related code would be released at https://github.com/RLHF-V/RLAIF-V/issues/6, but I find this [link](https://github.com/RLHF-V/RLAIF-V#data-generation) is empty. Where can I find this?

**Comment by Haoye17** [comment]
Hi @Gaffey! Thank you for your interest~

The data generation code and instructions can be downloaded [here](https://drive.google.com/drive/folders/1C6O752wV0Zy-Moc-BLNGjlLQ3GNO3tv9?usp=drive_link).

If there are any other questions, we are willing to help!
