### ISSUE TITLE
batch size=1 , only a Nvidia a100 memory=80, why display cuda out of memory?

### ISSUE THREAD

**Issue by AderonHuang** [RLHF-V/RLAIF-V#22]
![image](https://github.com/user-attachments/assets/eb0d7f49-2745-47d8-b728-04eca8225b3b)

**Comment by AderonHuang** [comment]
@Haoye17 @yiranyyu @Yunkai696 @lalulxm  can you meet this promble?, 1 a100 memory=80GG, but can't run while batch size=1,max length=1024

**Comment by yiranyyu** [comment]
We use 8 A100 to train to model during our experiments. You might need at least six A100 gpus to run the training. 
We just implemented the LoRA training code this week and will be released soon, which largely reduces the gpu memory usage.

**Comment by AderonHuang** [comment]
> We use 8 A100 to train the model during our experiments. You might need at least six A100 gpus to run the training. We just implemented the LoRA training code this week and will be released soon, which largely reduces the gpu memory usage.
ok，but some advice to offer you, maybe some images are damaged, code need set try-except,like this error
![Uploading image.png…]()

**Comment by phkhub** [comment]
@AderonHuang 
Have you solved the problem? Use an A100 to run full parameters, is there any way to optimize the cuda memory?

**Comment by miyapeng** [comment]
@yiranyyu Great answer, I want to know when to release LoRA training code? Thank you

**Comment by yiranyyu** [comment]
> @yiranyyu Great answer, I want to know when to release LoRA training code? Thank you

Sorry for busy on other projects. The LoRA training support is most likely coming in this week!

**Comment by lufanma** [comment]
> ![image](https://private-user-images.githubusercontent.com/43173636/361427011-9c449052-6152-44b9-9880-da728f9071fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxOTkyNTAsIm5iZiI6MTczMzE5ODk1MCwicGF0aCI6Ii80MzE3MzYzNi8zNjE0MjcwMTEtOWM0NDkwNTItNjE1Mi00NGI5LTk4ODAtZGE3MjhmOTA3MWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA0MDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNmJmNGViN2RiYjllNTM4ZjJhMDUzOTllNzYwOGJmZTEwMzU3NWIxMGFiMDFmZmNlMGQ5YTZlNTllMDRkNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1zylI3jG790fmYWJh3gWMqqXGBk7hnSscXZ15KpYXgU) thansk for your reply imediately, I also want to konw my training loss is normal or not correct?, why every data progress bar is 2672? I found default training script that default batch size is 1, and epoch is 10, not same as paper batchsize 8, epochs is 4 @yiranyyu @Yunkai696 @Haoye17 @lalulxm

Hi, when keep the same training setting, especially batchsize is 1, how about your training loss? It is strange that my loss does not converge will, and becomes larger or smaller every iteration.
