### ISSUE TITLE
about the RefoMB evaluation experiment

### ISSUE THREAD

**Issue by Molly-3000** [RLHF-V/RLAIF-V#24]
Excellent work！

I have some trouble with RefoMB evaluation experiment. It seems that ./RefoMB/eval_RefoMB_dev.py barely asked gpt4 to compare two generated answers and  offer a choice over them. The final output is a score corresponding to the choices. 

How can we get the evaluation results shown in the paper?
![image](https://github.com/user-attachments/assets/47d5d1f2-9fe9-4a56-91b6-09409b450d94)

so confused. help please @yiranyyu

**Comment by Haoye17** [comment]
Hi @Molly-3000 ,

Thank you for your interest~ 

We now open source the RefoMB evaluation code. You can follow the instructions [here](https://github.com/RLHF-V/RLAIF-V/tree/main?tab=readme-ov-file#refomb) to evaluate the win rate and trustworthiness score for each model.
