### ISSUE TITLE
where to find the lora fine-tuned checkpoints?

### ISSUE THREAD

**Issue by lufanma** [RLHF-V/RLAIF-V#32]
非常有意义的工作，非常感谢，请教一下在最新commit中chat.py中加载的模型 'RLAIF-V/RLAIF-V-7B/lora_checkpoints' 没有找到，在HF上只找到了https://huggingface.co/openbmb/RLAIF-V-7B/tree/main。

请问能够提供最新模型吗？感恩~ @yiranyyu

**Comment by yiranyyu** [comment]
我们目前仅在少量数据上确认了 LoRA 训练和推理代码的正确性，并没有用 LoRA 完整复现 RLAIF-V 论文的结果。您可以按照论文中描述的步骤使用 LoRA 进行训练来获得权重。

We have only verified the correctness of the LoRA training and inference code on a small dataset and have not fully reproduced the results of the RLAIF-V paper using LoRA. You can follow the steps described in the paper to train with LoRA and obtain the weights.

**Comment by lufanma** [comment]
> 我们目前仅在少量数据上确认了 LoRA 训练和推理代码的正确性，并没有用 LoRA 完整复现 RLAIF-V 论文的结果。您可以按照论文中描述的步骤使用 LoRA 进行训练来获得权重。
> 
> We have only verified the correctness of the LoRA training and inference code on a small dataset and have not fully reproduced the results of the RLAIF-V paper using LoRA. You can follow the steps described in the paper to train with LoRA and obtain the weights.

感谢回复~
