### ISSUE TITLE
Error when initing

### ISSUE THREAD

**Issue by pspdada** [RLHF-V/RLAIF-V#34]
I followed the initing instruction:
```
git clone https://github.com/RLHF-V/RLAIF-V.git
cd RLAIF-V
conda create -n rlaifv python=3.10 -y
conda activate rlaifv
pip install -e .
wget https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.7.3/en_core_web_trf-3.7.3.tar.gz
pip install en_core_web_trf-3.7.3.tar.gz
```
And used `RLAIFVChat` to play:
``` python
from chat import RLAIFVChat

chat_model = RLAIFVChat("/root/llm-project/utils/models/models-repo/RLAIF-V-7B/")  # or 'openBMB/RLAIF-V-12B'
image_path = "./examples/test.jpeg"
msgs = "Describe in detail the people in the picture."
inputs = {"image": image_path, "question": msgs}
answer = chat_model.chat(inputs)
print(answer)
```
But encountered an error:
```
Traceback (most recent call last):
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1345, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/generation/utils.py", line 27, in <module>
    from ..integrations.deepspeed import is_deepspeed_zero3_enabled
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/integrations/deepspeed.py", line 49, in <module>
    from accelerate.utils.deepspeed import HfDeepSpeedConfig as DeepSpeedConfig
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/accelerate/__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/accelerate/accelerator.py", line 34, in <module>
    from huggingface_hub import split_torch_state_dict_into_shards
ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/huggingface_hub/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1345, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 34, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 41, in <module>
    from .generation import GenerationConfig, GenerationMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1335, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1347, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/huggingface_hub/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/llm-project/RLAIF-V/test.py", line 1, in <module>
    from chat import RLAIFVChat
  File "/root/llm-project/RLAIF-V/chat.py", line 4, in <module>
    from llava.constants import IMAGE_TOKEN_INDEX, DEFAULT_IMAGE_TOKEN, DEFAULT_IM_START_TOKEN, DEFAULT_IM_END_TOKEN
  File "/root/llm-project/RLAIF-V/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/root/llm-project/RLAIF-V/llava/model/__init__.py", line 1, in <module>
    from .language_model.llava_llama import LlavaLlamaForCausalLM, LlavaConfig
  File "/root/llm-project/RLAIF-V/llava/model/language_model/llava_llama.py", line 21, in <module>
    from transformers import AutoConfig, AutoModelForCausalLM, \
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1336, in __getattr__
    value = getattr(module, name)
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1335, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1347, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/huggingface_hub/__init__.py)
```
How can I do to solve this problem?

**Comment by Racktic** [comment]
> I followed the initing instruction:
> 
> ```
> git clone https://github.com/RLHF-V/RLAIF-V.git
> cd RLAIF-V
> conda create -n rlaifv python=3.10 -y
> conda activate rlaifv
> pip install -e .
> wget https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.7.3/en_core_web_trf-3.7.3.tar.gz
> pip install en_core_web_trf-3.7.3.tar.gz
> ```
> 
> And used `RLAIFVChat` to play:
> 
> ```python
> from chat import RLAIFVChat
> 
> chat_model = RLAIFVChat("/root/llm-project/utils/models/models-repo/RLAIF-V-7B/")  # or 'openBMB/RLAIF-V-12B'
> image_path = "./examples/test.jpeg"
> msgs = "Describe in detail the people in the picture."
> inputs = {"image": image_path, "question": msgs}
> answer = chat_model.chat(inputs)
> print(answer)
> ```
> 
> But encountered an error:
> 
> ```
> Traceback (most recent call last):
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1345, in _get_module
>     return importlib.import_module("." + module_name, self.__name__)
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/generation/utils.py", line 27, in <module>
>     from ..integrations.deepspeed import is_deepspeed_zero3_enabled
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/integrations/deepspeed.py", line 49, in <module>
>     from accelerate.utils.deepspeed import HfDeepSpeedConfig as DeepSpeedConfig
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/accelerate/__init__.py", line 16, in <module>
>     from .accelerator import Accelerator
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/accelerate/accelerator.py", line 34, in <module>
>     from huggingface_hub import split_torch_state_dict_into_shards
> ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/huggingface_hub/__init__.py)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1345, in _get_module
>     return importlib.import_module("." + module_name, self.__name__)
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 34, in <module>
>     from ...modeling_utils import PreTrainedModel
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 41, in <module>
>     from .generation import GenerationConfig, GenerationMixin
>   File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1335, in __getattr__
>     module = self._get_module(self._class_to_module[name])
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1347, in _get_module
>     raise RuntimeError(
> RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
> cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/huggingface_hub/__init__.py)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/root/llm-project/RLAIF-V/test.py", line 1, in <module>
>     from chat import RLAIFVChat
>   File "/root/llm-project/RLAIF-V/chat.py", line 4, in <module>
>     from llava.constants import IMAGE_TOKEN_INDEX, DEFAULT_IMAGE_TOKEN, DEFAULT_IM_START_TOKEN, DEFAULT_IM_END_TOKEN
>   File "/root/llm-project/RLAIF-V/llava/__init__.py", line 1, in <module>
>     from .model import LlavaLlamaForCausalLM
>   File "/root/llm-project/RLAIF-V/llava/model/__init__.py", line 1, in <module>
>     from .language_model.llava_llama import LlavaLlamaForCausalLM, LlavaConfig
>   File "/root/llm-project/RLAIF-V/llava/model/language_model/llava_llama.py", line 21, in <module>
>     from transformers import AutoConfig, AutoModelForCausalLM, \
>   File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1336, in __getattr__
>     value = getattr(module, name)
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1335, in __getattr__
>     module = self._get_module(self._class_to_module[name])
>   File "/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1347, in _get_module
>     raise RuntimeError(
> RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
> Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
> cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/root/anaconda3/envs/rlaifv/lib/python3.10/site-packages/huggingface_hub/__init__.py)
> ```
> 
> How can I do to solve this problem?

Thank you for your interest! Refer to [this](https://stackoverflow.com/questions/78920095/cannot-import-name-split-torch-state-dict-into-shards-from-huggingface-hub) , you may check whether the version of `huggingface_hub` >=`0.23.0` and switch the version of `accelerate` to `0.31.0`

**Comment by pspdada** [comment]
Using `pip install huggingface_hub==0.23.0` successfully fix the RuntimeError. For convenience, could you update the settings in the `pyproject.toml` file?

**Comment by Racktic** [comment]
Hi, **@pspdada** ! Thanks for your suggestion, we have already update the `pyproject.toml`!
