### ISSUE TITLE
Data file not normal when opening "obj_halbench_300_with_image.jsonl"

### ISSUE THREAD

**Issue by hxhcreate** [RLHF-V/RLAIF-V#4]
[obj_halbench_300_with_image.jsonl](https://github.com/RLHF-V/RLAIF-V/blob/main/eval/data/obj_halbench_300_with_image.jsonl) 
the above file seems not normal at all?
![image](https://github.com/RLHF-V/RLAIF-V/assets/71424268/a7076605-dc91-4981-ba23-87e87d6b2d8b)

thansk for your help as we are reproducing your results

**Comment by yiranyyu** [comment]
Thank you for your interest!

It appears that the file was not successfully uploaded. We will re-upload a revised version within a day.

**Comment by Haoye17** [comment]
Hi @hxhcreate,

We have uploaded the correct file [here](https://github.com/RLHF-V/RLAIF-V/blob/main/eval/data/obj_halbench_300_with_image.jsonl). The `image` value is base64 encoded, and you can refer to our inference [code](https://github.com/RLHF-V/RLAIF-V/blob/main/muffin/eval/muffin_vqa.py#L59) to decode it back to a normal image.

Thank you again for your interest! If you have any other questions, please don't hesitate to ask. We're here to help!
